const id = Number(document.body.dataset.theme || 1);
const concepts = ['Obsidian','Atelier','Console','Nebula','Dock'];
const captions = ['Précis · sobre · familier','Clair · calme · aéré','Dense · clavier · technique','Immersif · doux · contrasté','Structuré · lisible · utilitaire'];
document.title = `${concepts[id-1]} — Maquette ${id}`;
document.body.innerHTML = `
<header class="top"><div class="brand"><i>▰</i>${concepts[id-1]}</div><span class="label">${captions[id-1]}</span><button class="search" data-palette>⌕ &nbsp; Rechercher une commande <kbd>Leader P</kbd></button><span class="window" aria-hidden="true">− □ ×</span></header>
<div class="shell"><main class="main"><div class="context"><div><h1 id="workspace-title">Terminal Studio</h1><small id="workspace-subtitle">3 onglets &nbsp; / &nbsp; Dernière activité à l’instant</small></div><span class="branch">⑂ feat/workspaces</span></div>
<div class="tabs" role="tablist" aria-label="Terminaux"><button class="tab active" role="tab" aria-selected="true"><span class="dot"></span>Développement<em>×</em></button><button class="tab" role="tab" aria-selected="false">Serveur<em>×</em></button><button class="tab" role="tab" aria-selected="false">Git Bash<em>×</em></button><button class="plus" aria-label="Nouvel onglet">+</button></div>
<div class="tools"><span>⌁ &nbsp; C:\\Projets\\terminal-studio</span><button data-demo="Split vertical : aperçu uniquement">◫ &nbsp; Split</button><button data-demo="Split horizontal : aperçu uniquement">⬒</button><button data-palette>···</button></div>
<div class="terminals"><section class="pane primary"><div class="pane-head"><strong>❯ &nbsp; PowerShell · Agent</strong><span>01 &nbsp; ◫</span></div><div class="code"><div class="restored">Session restaurée · 09:41</div><p class="dim">✓ Configuration chargée<br>✓ 3 workspaces restaurés</p><p><span class="accent">C:\\Projets\\terminal-studio</span><br><span class="green">❯</span> agent</p><div class="agentbox"><strong>Organisation des workspaces</strong><br><span class="dim">Je prépare la navigation entre les onglets<br>et la sauvegarde de la disposition.</span></div><p><span class="green">✓</span> Analyse des composants terminée<br><span class="green">✓</span> Structure des onglets mise à jour<br><span class="yellow">●</span> Une décision reste à confirmer</p><div class="waitbox"><span class="yellow">Votre réponse est attendue</span><br>Conserver le workspace après la fermeture<br>de son dernier onglet ?</div><p class="dim">› Écrivez votre réponse… <span class="cursor"></span></p></div></section>
<section class="pane"><div class="pane-head"><strong>❯ &nbsp; PowerShell · Serveur</strong><span>02</span></div><div class="code"><p><span class="accent">…\\terminal-studio</span><br><span class="green">❯</span> npm run dev</p><p><strong>VITE</strong> <span class="green">ready in 284 ms</span></p><p>&nbsp; Local: &nbsp; <span class="accent">http://localhost:5173/</span><br><span class="dim">&nbsp; press h + enter to show help</span></p><p class="dim">10:24:08 &nbsp; page reload src/App.tsx</p></div></section>
<section class="pane"><div class="pane-head"><strong>❯ &nbsp; PowerShell</strong><span>03</span></div><div class="code"><p><span class="accent">…\\terminal-studio</span> <span class="dim">⑂ feat/workspaces</span><br><span class="green">❯</span> git status --short</p><p><span class="yellow"> M</span> src/Workspace.tsx<br><span class="yellow"> M</span> src/Terminal.tsx<br><span class="green">??</span> src/Sidebar.tsx</p><span class="green">❯</span> <span class="cursor"></span></div></section></div></main>
<aside class="sidebar"><div class="handle" role="separator" aria-label="Largeur du panneau" aria-orientation="vertical" tabindex="0"></div><div class="side-head"><h2>Workspaces <span class="dim">/ 3</span></h2><button data-demo="Création de workspace : aperçu uniquement" aria-label="Créer un workspace">+</button></div><div class="section-label">Vos espaces</div>
<button class="workspace selected" data-workspace="Terminal Studio"><span class="count">3</span><strong><span class="icon">T</span>Terminal Studio</strong><small>Développement du terminal</small><span class="attention">● &nbsp; Une réponse attendue</span></button><div class="children"><button data-focus>↳ &nbsp; Développement &nbsp; ●</button><button data-tab="Serveur">↳ &nbsp; Serveur</button><button data-tab="Git Bash">↳ &nbsp; Git Bash</button></div>
<button class="workspace" data-workspace="Perso"><span class="count">3</span><strong><span class="icon">P</span>Perso</strong><small>Documents · Scripts · Notes</small></button><button class="workspace" data-workspace="API Boutique"><span class="count">2</span><strong><span class="icon">A</span>API Boutique</strong><small>Dernière activité il y a 12 min</small></button>
<div class="section-label">Accès rapide</div><button class="workspace" data-projects><strong>⌕ &nbsp; Ouvrir un projet</strong><small>Parcourir votre dossier Projets</small></button><div class="side-bottom"><div class="notice"><strong>● &nbsp; Besoin de vous</strong><p>Terminal Studio attend une décision.<br><button data-focus style="padding:5px 0;color:var(--accent)">Rejoindre le terminal ↗</button></p></div><div class="settings"><button data-demo="Préférences : aperçu uniquement">⚙ &nbsp; Préférences</button><span>Local</span></div></div></aside></div>
<footer class="status"><span><span class="dot"></span> &nbsp; PowerShell 7</span><span>UTF-8</span><span>Leader : Espace</span><span class="saved">✓ Disposition enregistrée</span><span>MAQUETTE ${id} / 5</span></footer>
<nav class="switcher" aria-label="Comparer les propositions"><a href="index.html">← Galerie</a><span>|</span>${concepts.map((n,i)=>`<a class="${i+1===id?'current':''}" href="${i+1}.html">${i+1} ${n}</a>`).join('')}</nav>
<dialog><input aria-label="Rechercher" placeholder="Rechercher une commande, un workspace…"><div class="results"></div><footer>Maquette interactive · Aucune commande réelle exécutée · Échap pour fermer</footer></dialog>`;
const dialog = document.querySelector('dialog'), input = dialog.querySelector('input'), results = dialog.querySelector('.results');
let choices=[];
function toast(message){document.querySelector('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.setAttribute('role','status');el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),3500)}
function openPalette(projects=false){choices=projects?['terminal-studio','api-boutique','site-personnel','scripts']:['Rejoindre Terminal Studio','Rejoindre Perso','Rejoindre API Boutique','Renommer le workspace','Renommer l’onglet','Split vertical','Split horizontal','Rouvrir un onglet fermé','Ouvrir dans l’éditeur','Copier le chemin'];input.value='';input.placeholder=projects?'Chercher dans C:\\Projets…':'Rechercher une commande, un workspace…';render();dialog.showModal();input.focus()}
function render(){results.replaceChildren();choices.filter(x=>x.toLocaleLowerCase().includes(input.value.toLocaleLowerCase())).forEach(label=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>{dialog.close();if(label.startsWith('Rejoindre '))selectWorkspace(label.slice(10));else toast(`${label} — simulation de l’action`)};results.append(b)})}
input.oninput=render;document.querySelectorAll('[data-palette]').forEach(b=>b.onclick=()=>openPalette());document.querySelectorAll('[data-projects]').forEach(b=>b.onclick=()=>openPalette(true));dialog.onclick=e=>{if(e.target===dialog)dialog.close()};
function selectWorkspace(name){document.getElementById('workspace-title').textContent=name;document.querySelectorAll('[data-workspace]').forEach(b=>b.classList.toggle('selected',b.dataset.workspace===name));document.getElementById('workspace-subtitle').textContent=name==='Terminal Studio'?'3 onglets / Dernière activité à l’instant':'Aperçu de navigation · contenu des terminaux illustratif';toast(`Workspace « ${name} » sélectionné — terminaux de démonstration`)}
document.querySelectorAll('[data-workspace]').forEach(b=>b.onclick=()=>selectWorkspace(b.dataset.workspace));
function selectTab(b){document.querySelectorAll('.tab').forEach(t=>{t.classList.toggle('active',t===b);t.setAttribute('aria-selected',String(t===b))});toast(`Onglet ${b.childNodes[1]?.textContent||b.textContent.replace('×','')} — aperçu de sélection`)}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>selectTab(b));document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{const t=[...document.querySelectorAll('.tab')].find(t=>t.textContent.includes(b.dataset.tab));if(t)selectTab(t)});
document.querySelector('.plus').onclick=()=>{const b=document.createElement('button');b.className='tab';b.setAttribute('role','tab');b.textContent='PowerShell';b.onclick=()=>selectTab(b);document.querySelector('.tabs').insertBefore(b,document.querySelector('.plus'));selectTab(b)};
document.querySelectorAll('[data-demo]').forEach(b=>b.onclick=()=>toast(b.dataset.demo));document.querySelectorAll('[data-focus]').forEach(b=>b.onclick=()=>{selectWorkspace('Terminal Studio');const p=document.querySelector('.primary');p.scrollIntoView({block:'nearest',behavior:'smooth'});p.animate([{boxShadow:'0 0 0 3px var(--accent)'},{boxShadow:'none'}],{duration:1200});toast('Pane nécessitant une réponse sélectionné')});
const handle=document.querySelector('.handle'),sidebar=document.querySelector('.sidebar');handle.onpointerdown=e=>{handle.setPointerCapture(e.pointerId);handle.onpointermove=e=>{sidebar.style.width=Math.max(225,Math.min(450,innerWidth-e.clientX-18))+'px'};handle.onpointerup=()=>handle.onpointermove=null};handle.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();sidebar.style.width=Math.max(225,Math.min(450,sidebar.offsetWidth+(e.key==='ArrowLeft'?15:-15)))+'px'}};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='p'){e.preventDefault();if(!dialog.open)openPalette()}});
