export enum IconName {
  Branch = 'branch',
  Check = 'check',
  Chevron = 'chevron',
  Close = 'close',
  Discard = 'discard',
  Editor = 'editor',
  Explorer = 'explorer',
  Fetch = 'fetch',
  File = 'file',
  Folder = 'folder',
  Minus = 'minus',
  More = 'more',
  NewFile = 'newFile',
  NewFolder = 'newFolder',
  Plus = 'plus',
  Project = 'project',
  Pull = 'pull',
  Push = 'push',
  Refresh = 'refresh',
  Stash = 'stash',
  Switch = 'switch',
  Tag = 'tag',
  Undo = 'undo',
}
